/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Home;

import java.sql.Connection;
import java.util.ArrayList;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author felip
 */
public class Quiz extends javax.swing.JFrame {
    CrudBD cBD =new CrudBD();
    Connection conn =ConnFactory.conectar();
    Usuario us =new Usuario();
    
    ArrayList<String> perguntas =cBD.mostrarPerguntas(conn);
    ArrayList<String> respostas =cBD.mostrarResposta(conn);
    String[][] opcoes ={{"amarelo", "azul", "vermelha", "roxo"}, {"verde", "azul", "vermelho", "roxo"}, {"laranja", "azul", "preto", "roxo"}, {"amarelo", "azul", "vermelho", "roxo"}, {"bananas", "biscoitos", "vermelho", "roxo"},};
    int index, numeroAcertos =0;
    int tempo, mult;
    private boolean pausarTimer =false;

    ButtonGroup bg =new ButtonGroup();

    /**
     * Creates new form Quiz
     */
    public Quiz() {
        initComponents();
        
        bg.add(botaoRadio1);
        bg.add(botaoRadio2);
        bg.add(botaoRadio3);
        bg.add(botaoRadio4);
        botaoProximoActionPerformed(null);
    }
    
    public int getTempo(){
        return tempo;
    }
    public void setTempo(int t){
        tempo=t;
    }
    
    public int getMult(){
        return mult;
    }
    public void setMult(int m){
        mult=m;
    }
    
    
    public void getSelectedOption(JRadioButton rB){
        
        
        System.out.println(rB.getText());
        System.out.println(respostas.get(index));
        
        if(rB.getText().equals(respostas.get(index))){
            numeroAcertos++;
            
        }
        
        index++;
        enableRButton(false);   
    }
    
    public void enableRButton(boolean yes_or_no){
        botaoRadio1.setEnabled(yes_or_no);
        botaoRadio2.setEnabled(yes_or_no);
        botaoRadio3.setEnabled(yes_or_no);
        botaoRadio4.setEnabled(yes_or_no);
    }
    
    public void calcularPontos(){
        if(getTempo()>=200){
            setMult(10);
        }
        else if(getTempo()>=160){
            setMult(8);
        }
        else if(getTempo()>=100){
            setMult(6);
        }
        else{
            setMult(4);
        }
    }

    public void iniciarTimer() {
        Thread countdownThread = new Thread(new Runnable() {
            @Override
            public void run() {
                for (int i = 300; i >= 0; i--) {
                    if (pausarTimer) {
                        // Pausar o timer
                        while (pausarTimer) {
                            try {
                                Thread.sleep(1000);
                            } catch (Exception e) {
                                System.out.println("Error: " + e);
                            }
                        }
                    }
                    System.out.println(i + " ");
                    setTempo(i);
                    try {
                        Thread.sleep(1000);
                    } catch (Exception e) {
                        System.out.println("Error: " + e);
                    }
                }
                System.out.println("\nFinished");
            }
        });
        countdownThread.start();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cabecario = new javax.swing.JLabel();
        botaoRadio3 = new javax.swing.JRadioButton();
        botaoRadio2 = new javax.swing.JRadioButton();
        botaoRadio4 = new javax.swing.JRadioButton();
        botaoRadio1 = new javax.swing.JRadioButton();
        botaoSair = new javax.swing.JButton();
        botaoProximo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 400));

        cabecario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cabecario.setText("<<<Questão>>>");

        botaoRadio3.setText("jRadioButton3");
        botaoRadio3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRadio3ActionPerformed(evt);
            }
        });

        botaoRadio2.setText("jRadioButton2");
        botaoRadio2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRadio2ActionPerformed(evt);
            }
        });

        botaoRadio4.setText("jRadioButton4");
        botaoRadio4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRadio4ActionPerformed(evt);
            }
        });

        botaoRadio1.setText("jRadioButton1");
        botaoRadio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRadio1ActionPerformed(evt);
            }
        });

        botaoSair.setText("Sair");
        botaoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSairActionPerformed(evt);
            }
        });

        botaoProximo.setText("Próximo");
        botaoProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoProximoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cabecario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoRadio2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoRadio4, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoRadio3, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoRadio1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(botaoSair, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoProximo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 250, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(cabecario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botaoRadio1)
                .addGap(18, 18, 18)
                .addComponent(botaoRadio2)
                .addGap(18, 18, 18)
                .addComponent(botaoRadio3)
                .addGap(18, 18, 18)
                .addComponent(botaoRadio4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoSair, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoProximo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSairActionPerformed
        // TODO add your handling code here:
        pausarTimer=true;
        Interface iN =new Interface();
        iN.setVisible(true);
        iN.pack();
        this.dispose();
    }//GEN-LAST:event_botaoSairActionPerformed

    private void botaoProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoProximoActionPerformed
       
        
        if(botaoProximo.getText().equals("Reiniciar o Quiz")){
            //Reiniciar o Quiz
            botaoProximo.setText("Próximo");
            index =0;
            numeroAcertos =0;
        }
        
        if(index ==perguntas.size()){
            calcularPontos();
            us.setPontos(numeroAcertos*mult);
            us.setRa(JOptionPane.showInputDialog("Digite o seu RA: "));
            cBD.consultarUser(us);
            cabecario.setText("Pontuação: "+us.getPontos());
            System.out.println(us.getRa());
            System.out.println(us.getNome());
            System.out.println(us.getPontos());
            cBD.incluirRank(us);
            
            botaoProximo.setText("Reiniciar o Quiz");

        }
        else{
            //habilitar os botões
            enableRButton(true);
        
            //Mostrar próxima pergunta
            cabecario.setText(perguntas.get(index));
            botaoRadio1.setText(opcoes[index][0]);
            botaoRadio2.setText(opcoes[index][1]);
            botaoRadio3.setText(opcoes[index][2]);
            botaoRadio4.setText(opcoes[index][3]);
            
            if(index ==perguntas.size()-1){
                botaoProximo.setText("Finalizar");
            }
        }
        if(botaoProximo.getText().equals("Finalizar")){
            pausarTimer=true;
        }
        else{
            pausarTimer=false;
        }
        //Limpar seleção
        bg.clearSelection();
    }//GEN-LAST:event_botaoProximoActionPerformed

    private void botaoRadio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRadio1ActionPerformed
        getSelectedOption(botaoRadio1);
    }//GEN-LAST:event_botaoRadio1ActionPerformed

    private void botaoRadio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRadio2ActionPerformed
        getSelectedOption(botaoRadio2);
    }//GEN-LAST:event_botaoRadio2ActionPerformed

    private void botaoRadio3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRadio3ActionPerformed
        getSelectedOption(botaoRadio3);
    }//GEN-LAST:event_botaoRadio3ActionPerformed

    private void botaoRadio4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRadio4ActionPerformed
        getSelectedOption(botaoRadio4);
    }//GEN-LAST:event_botaoRadio4ActionPerformed
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Quiz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoProximo;
    private javax.swing.JRadioButton botaoRadio1;
    private javax.swing.JRadioButton botaoRadio2;
    private javax.swing.JRadioButton botaoRadio3;
    private javax.swing.JRadioButton botaoRadio4;
    private javax.swing.JButton botaoSair;
    private javax.swing.JLabel cabecario;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
